# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5610bfd6094aaadac900421bd711a6c66efc7bff007c1ac601b5f3d32d02989a17e1dcd0c2c92810e342f339ee88c4865970e10cfb297734866e7365e1c9d0f

test:
  secret_key_base: e742cb78af55cc7e060d2cd0aeec05c4f22239b15839a759b2d7d4eed33d61987731772dd4cb8d0c6a0195096f17825de83744f20268dc0d242c4490bd679afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
